//! Hopper-owned host execution harness for Hopper programs.
//!
//! `HopperSvm` executes the host-callable bridge generated by
//! `#[hopper::program]` against aligned Hopper Native account buffers.
//! It is intentionally small: framework tests get real `AccountView` memory,
//! borrow tracking, and host-emulated system transfers without depending on an
//! external validator harness.

use hopper_native::{raw_account::RuntimeAccount, AccountView as NativeAccountView};
use hopper_runtime::{AccountView, Address, ProgramResult};
use std::sync::Mutex;

static PROCESS_LOCK: Mutex<()> = Mutex::new(());

/// Host-callable Hopper program dispatcher.
pub type ProcessInstruction =
    for<'info> fn(&'info Address, &'info [AccountView<'info>], &'info [u8]) -> ProgramResult;

/// Account fixture consumed and produced by [`HopperSvm`].
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AccountFixture {
    pub address: Address,
    pub owner: Address,
    pub lamports: u64,
    pub data: Vec<u8>,
    pub is_signer: bool,
    pub is_writable: bool,
    pub executable: bool,
}

impl AccountFixture {
    pub fn new(address: Address, owner: Address, lamports: u64, data_len: usize) -> Self {
        Self {
            address,
            owner,
            lamports,
            data: vec![0; data_len],
            is_signer: false,
            is_writable: false,
            executable: false,
        }
    }

    pub fn with_data(address: Address, owner: Address, lamports: u64, data: Vec<u8>) -> Self {
        Self {
            address,
            owner,
            lamports,
            data,
            is_signer: false,
            is_writable: false,
            executable: false,
        }
    }

    pub fn signer(mut self) -> Self {
        self.is_signer = true;
        self
    }

    pub fn writable(mut self) -> Self {
        self.is_writable = true;
        self
    }

    pub fn executable(mut self) -> Self {
        self.executable = true;
        self
    }
}

/// Result of a host instruction execution.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProcessResult {
    pub program_result: ProgramResult,
    pub resulting_accounts: Vec<AccountFixture>,
    pub compute_units_consumed: u64,
}

/// Minimal Hopper-owned execution harness.
#[derive(Clone, Debug, Default)]
pub struct HopperSvm;

impl HopperSvm {
    pub fn new() -> Self {
        Self
    }

    pub fn process_instruction(
        &self,
        program_id: Address,
        instruction_data: &[u8],
        accounts: &[AccountFixture],
        process: ProcessInstruction,
    ) -> ProcessResult {
        let _guard = PROCESS_LOCK
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner());
        let mut backing: Vec<BackingAccount> = accounts.iter().map(BackingAccount::new).collect();
        let program_result = {
            let native_views: Vec<NativeAccountView<'_>> = backing
                .iter_mut()
                .map(|account| unsafe { NativeAccountView::new_unchecked(account.raw_mut()) })
                .collect();
            let runtime_accounts =
                unsafe { hopper_runtime::native_boundary::wrap_account_slice(&native_views) };
            process(&program_id, runtime_accounts, instruction_data)
        };

        ProcessResult {
            program_result,
            resulting_accounts: backing.iter().map(BackingAccount::to_fixture).collect(),
            compute_units_consumed: 0,
        }
    }
}

struct BackingAccount {
    words: Vec<u64>,
}

impl BackingAccount {
    fn new(account: &AccountFixture) -> Self {
        let byte_len = RuntimeAccount::SIZE + account.data.len();
        let word_len = byte_len.div_ceil(core::mem::size_of::<u64>());
        let mut backing = Self {
            words: vec![0; word_len],
        };
        unsafe {
            let raw = backing.raw_mut();
            raw.write(RuntimeAccount {
                borrow_state: hopper_native::NOT_BORROWED,
                is_signer: account.is_signer as u8,
                is_writable: account.is_writable as u8,
                executable: account.executable as u8,
                resize_delta: 0,
                address: to_native_address(&account.address),
                owner: to_native_address(&account.owner),
                lamports: account.lamports,
                data_len: account.data.len() as u64,
            });
            core::ptr::copy_nonoverlapping(
                account.data.as_ptr(),
                (raw as *mut u8).add(RuntimeAccount::SIZE),
                account.data.len(),
            );
        }
        backing
    }

    fn to_fixture(&self) -> AccountFixture {
        unsafe {
            let raw = &*self.raw();
            let data_len = raw.data_len as usize;
            let data = core::slice::from_raw_parts(
                (self.raw() as *const u8).add(RuntimeAccount::SIZE),
                data_len,
            )
            .to_vec();
            AccountFixture {
                address: from_native_address(&raw.address),
                owner: from_native_address(&raw.owner),
                lamports: raw.lamports,
                data,
                is_signer: raw.is_signer != 0,
                is_writable: raw.is_writable != 0,
                executable: raw.executable != 0,
            }
        }
    }

    fn raw(&self) -> *const RuntimeAccount {
        self.words.as_ptr() as *const RuntimeAccount
    }

    fn raw_mut(&mut self) -> *mut RuntimeAccount {
        self.words.as_mut_ptr() as *mut RuntimeAccount
    }
}

fn to_native_address(address: &Address) -> hopper_native::Address {
    hopper_native::Address::new_from_array(address.to_bytes())
}

fn from_native_address(address: &hopper_native::Address) -> Address {
    Address::new_from_array(address.to_bytes())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ok_process<'info>(
        _program_id: &'info Address,
        accounts: &'info [AccountView<'info>],
        _data: &'info [u8],
    ) -> ProgramResult {
        accounts[0].set_lamports(accounts[0].lamports() + 1)
    }

    #[test]
    fn process_round_trips_account_mutation() {
        let program_id = Address::new_from_array([9; 32]);
        let account =
            AccountFixture::new(Address::new_from_array([1; 32]), program_id, 41, 8).writable();
        let result = HopperSvm::new().process_instruction(program_id, &[], &[account], ok_process);
        assert!(result.program_result.is_ok());
        assert_eq!(result.resulting_accounts[0].lamports, 42);
    }
}
