[package]
name = "hopper-migration"
version = "0.2.1"
edition = "2021"
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
hopper = { path = "../..", package = "hopper-lang", default-features = false }
hopper-schema = { path = "../../crates/hopper-schema" }

[features]
default = ["migrate"]
hopper-native-backend = []
legacy-pinocchio-compat = []
solana-program-backend = []
migrate = ["hopper/migrate"]

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(target_os, values("solana"))'] }
