// Code generated by `hopper compile --emit go`; DO NOT EDIT.
// Program: hopper-lang v0.6.0
package hopperclient

import (
	"encoding/binary"
	"errors"
	"fmt"
)

var _ = binary.LittleEndian

const HeaderSize = 16
const LayoutIDOffset = 4
const LayoutIDLength = 8

type Pubkey [32]byte

type AccountMeta struct {
	Pubkey Pubkey
	IsSigner bool
	IsWritable bool
	Layout string
}

type Instruction struct {
	ProgramID Pubkey
	Accounts []AccountMeta
	Data []byte
}

var ErrBufferTooSmall = errors.New("hopper client: buffer too small")
var ErrTagMismatch = errors.New("hopper client: tag mismatch")
var ErrCompactSizeMismatch = errors.New("hopper client: compact account size mismatch")
var ErrDiscriminatorMismatch = errors.New("hopper client: account discriminator mismatch")

type LayoutMismatchError struct {
	Expected [8]byte
	Actual [8]byte
}

func (e LayoutMismatchError) Error() string {
	return fmt.Sprintf("hopper client: layout mismatch: expected %x got %x", e.Expected, e.Actual)
}

func readLayoutID(data []byte) ([8]byte, error) {
	var id [8]byte
	if len(data) < HeaderSize {
		return id, ErrBufferTooSmall
	}
	copy(id[:], data[LayoutIDOffset:LayoutIDOffset+LayoutIDLength])
	return id, nil
}

func assertLayoutID(data []byte, expected [8]byte) error {
	actual, err := readLayoutID(data)
	if err != nil {
		return err
	}
	if actual != expected {
		return LayoutMismatchError{Expected: expected, Actual: actual}
	}
	return nil
}

const SubmitDisc byte = 0
const SubmitDataLen = 45

type SubmitArgs struct {
	Orders [42]byte
	Nonce uint16
}

type SubmitAccounts struct {
	Authority Pubkey
}

func BuildSubmitInstruction(programID Pubkey, accounts SubmitAccounts, args SubmitArgs) (Instruction, error) {
	return Instruction{}, errors.New("hopper client: bounded instruction arguments require the Rust, TypeScript, or Python client")
}

const BytesDisc byte = 1
const BytesDataLen = 29

type BytesArgs struct {
	Bytes [10]byte
	Note [18]byte
}

type BytesAccounts struct {
	Authority Pubkey
}

func BuildBytesInstruction(programID Pubkey, accounts BytesAccounts, args BytesArgs) (Instruction, error) {
	return Instruction{}, errors.New("hopper client: bounded instruction arguments require the Rust, TypeScript, or Python client")
}

const AliasesDisc byte = 2
const AliasesDataLen = 34

type AliasesArgs struct {
	Quantities [10]byte
	Label [18]byte
	Nonce [2]byte
	Salt [3]byte
}

type AliasesAccounts struct {
	Authority Pubkey
}

func BuildAliasesInstruction(programID Pubkey, accounts AliasesAccounts, args AliasesArgs) (Instruction, error) {
	return Instruction{}, errors.New("hopper client: bounded instruction arguments require the Rust, TypeScript, or Python client")
}

