/* Auto-generated by `hopper compile --emit c`. DO NOT EDIT. */
/* Program: hopper-lang v0.6.0 */
#ifndef HOPPER_HOPPER_LANG_CLIENT_H
#define HOPPER_HOPPER_LANG_CLIENT_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

#define HOPPER_HEADER_SIZE 16u
#define HOPPER_LAYOUT_ID_OFFSET 4u
#define HOPPER_LAYOUT_ID_LENGTH 8u

typedef struct { uint8_t bytes[32]; } HopperPubkey;
typedef struct { HopperPubkey pubkey; bool is_signer; bool is_writable; const char *layout; } HopperAccountMeta;

typedef enum {
    HOPPER_CLIENT_OK = 0,
    HOPPER_CLIENT_BUFFER_TOO_SMALL = 1,
    HOPPER_CLIENT_LAYOUT_MISMATCH = 2,
    HOPPER_CLIENT_TAG_MISMATCH = 3,
    HOPPER_CLIENT_UNSUPPORTED_ENCODING = 4
} HopperClientError;

static inline uint16_t hopper_read_le_u16(const uint8_t *p) {
    return (uint16_t)p[0] | ((uint16_t)p[1] << 8);
}
static inline uint32_t hopper_read_le_u32(const uint8_t *p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static inline uint64_t hopper_read_le_u64(const uint8_t *p) {
    uint64_t out = 0;
    for (size_t i = 0; i < 8; i++) out |= ((uint64_t)p[i]) << (8u * i);
    return out;
}
static inline void hopper_write_le_u16(uint8_t *p, uint16_t v) {
    p[0] = (uint8_t)(v & 0xffu); p[1] = (uint8_t)((v >> 8) & 0xffu);
}
static inline void hopper_write_le_u32(uint8_t *p, uint32_t v) {
    for (size_t i = 0; i < 4; i++) p[i] = (uint8_t)((v >> (8u * i)) & 0xffu);
}
static inline void hopper_write_le_u64(uint8_t *p, uint64_t v) {
    for (size_t i = 0; i < 8; i++) p[i] = (uint8_t)((v >> (8u * i)) & 0xffu);
}
static inline HopperClientError hopper_assert_layout_id(const uint8_t *data, size_t data_len, const uint8_t expected[8]) {
    if (data_len < HOPPER_HEADER_SIZE) return HOPPER_CLIENT_BUFFER_TOO_SMALL;
    return memcmp(data + HOPPER_LAYOUT_ID_OFFSET, expected, HOPPER_LAYOUT_ID_LENGTH) == 0 ? HOPPER_CLIENT_OK : HOPPER_CLIENT_LAYOUT_MISMATCH;
}

#define HOPPER_SUBMIT_DISC 0u
#define HOPPER_SUBMIT_DATA_LEN 45u
#define HOPPER_SUBMIT_ACCOUNT_COUNT 1u

typedef struct {
    uint8_t orders[42];
    uint16_t nonce;
} HopperSubmitArgs;

typedef struct {
    HopperPubkey authority;
} HopperSubmitAccounts;

static inline size_t hopper_submit_account_metas(const HopperSubmitAccounts *accounts, HopperAccountMeta out[HOPPER_SUBMIT_ACCOUNT_COUNT]) {
    out[0].pubkey = accounts->authority;
    out[0].is_signer = true;
    out[0].is_writable = false;
    out[0].layout = "";
    return HOPPER_SUBMIT_ACCOUNT_COUNT;
}

static inline HopperClientError hopper_build_submit_data(const HopperSubmitArgs *args, uint8_t *out, size_t out_len, size_t *written) {
    (void)args; (void)out; (void)out_len; (void)written;
    return HOPPER_CLIENT_UNSUPPORTED_ENCODING;
}

#define HOPPER_BYTES_DISC 1u
#define HOPPER_BYTES_DATA_LEN 29u
#define HOPPER_BYTES_ACCOUNT_COUNT 1u

typedef struct {
    uint8_t bytes[10];
    uint8_t note[18];
} HopperBytesArgs;

typedef struct {
    HopperPubkey authority;
} HopperBytesAccounts;

static inline size_t hopper_bytes_account_metas(const HopperBytesAccounts *accounts, HopperAccountMeta out[HOPPER_BYTES_ACCOUNT_COUNT]) {
    out[0].pubkey = accounts->authority;
    out[0].is_signer = true;
    out[0].is_writable = false;
    out[0].layout = "";
    return HOPPER_BYTES_ACCOUNT_COUNT;
}

static inline HopperClientError hopper_build_bytes_data(const HopperBytesArgs *args, uint8_t *out, size_t out_len, size_t *written) {
    (void)args; (void)out; (void)out_len; (void)written;
    return HOPPER_CLIENT_UNSUPPORTED_ENCODING;
}

#define HOPPER_ALIASES_DISC 2u
#define HOPPER_ALIASES_DATA_LEN 34u
#define HOPPER_ALIASES_ACCOUNT_COUNT 1u

typedef struct {
    uint8_t quantities[10];
    uint8_t label[18];
    uint8_t nonce[2];
    uint8_t salt[3];
} HopperAliasesArgs;

typedef struct {
    HopperPubkey authority;
} HopperAliasesAccounts;

static inline size_t hopper_aliases_account_metas(const HopperAliasesAccounts *accounts, HopperAccountMeta out[HOPPER_ALIASES_ACCOUNT_COUNT]) {
    out[0].pubkey = accounts->authority;
    out[0].is_signer = true;
    out[0].is_writable = false;
    out[0].layout = "";
    return HOPPER_ALIASES_ACCOUNT_COUNT;
}

static inline HopperClientError hopper_build_aliases_data(const HopperAliasesArgs *args, uint8_t *out, size_t out_len, size_t *written) {
    (void)args; (void)out; (void)out_len; (void)written;
    return HOPPER_CLIENT_UNSUPPORTED_ENCODING;
}

#endif /* HOPPER_HOPPER_LANG_CLIENT_H */
