// Auto-generated by hopper client gen --kt
// Program: hopper-lang v0.6.0
// DO NOT EDIT

package hopper.generated.hopper_lang

import org.sol4k.PublicKey
import org.sol4k.instruction.AccountMeta
import org.sol4k.instruction.Instruction
import java.nio.ByteBuffer
import java.nio.ByteOrder

data class SubmitArgs(
    val orders: ByteArray,
    val nonce: UShort
)

data class SubmitAccounts(
    val authority: PublicKey
)

fun createSubmitInstruction(
    args: SubmitArgs,
    accounts: SubmitAccounts,
    programId: PublicKey,
): Instruction {
    throw UnsupportedOperationException("Bounded instruction arguments require the Rust, TypeScript, or Python client")
}

data class BytesArgs(
    val bytes: ByteArray,
    val note: ByteArray
)

data class BytesAccounts(
    val authority: PublicKey
)

fun createBytesInstruction(
    args: BytesArgs,
    accounts: BytesAccounts,
    programId: PublicKey,
): Instruction {
    throw UnsupportedOperationException("Bounded instruction arguments require the Rust, TypeScript, or Python client")
}

data class AliasesArgs(
    val quantities: ByteArray,
    val label: ByteArray,
    val nonce: ByteArray,
    val salt: ByteArray
)

data class AliasesAccounts(
    val authority: PublicKey
)

fun createAliasesInstruction(
    args: AliasesArgs,
    accounts: AliasesAccounts,
    programId: PublicKey,
): Instruction {
    throw UnsupportedOperationException("Bounded instruction arguments require the Rust, TypeScript, or Python client")
}

