[package]
name = "hopper-stablecoin-memo-pay"
version = "0.2.1"
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Devnet-ready Hopper stablecoin payment ledger with TransferChecked and Memo CPI."

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
hopper = { path = "../..", package = "hopper-lang", default-features = false, features = ["hopper-native-backend", "proc-macros"] }

[features]
default = ["hopper-native-backend"]
hopper-native-backend = ["hopper/hopper-native-backend"]
legacy-pinocchio-compat = ["hopper/legacy-pinocchio-compat"]
solana-program-backend = ["hopper/solana-program-backend"]

[lints]
workspace = true
