//! Compile-time segment mapping for zero-copy account layouts.
//!
//! `SegmentMap` provides a static description of the byte regions within a
//! struct layout. This is separate from `SegmentRegistry` (which manages
//! on-chain dynamic segment metadata). `SegmentMap` is compile-time knowledge
//! that proc macros (or hand-written impls) generate from struct definitions.
//!
//! ## Design Philosophy
//!
//! Segment offsets are evaluated at compile time and stored as constants.
//! This means segment lookups compile down to a const load — no string
//! matching, no branching, no heap. The generated code is the same shape
//! as raw Pinocchio pointer arithmetic.
//!
//! ## Example
//!
//! ```ignore
//! // Generated by #[hopper::state] or hand-written:
//! impl SegmentMap for Vault {
//!     const SEGMENTS: &'static [StaticSegment] = &[
//!         StaticSegment::new("authority", 0, 32),
//!         StaticSegment::new("balance", 32, 8),
//!         StaticSegment::new("bump", 40, 1),
//!     ];
//! }
//!
//! // Look up a segment:
//! let seg = Vault::segment("balance").unwrap();
//! assert_eq!(seg.offset, 32);
//! assert_eq!(seg.size, 8);
//! ```

/// A compile-time constant segment descriptor.
///
/// Describes a named byte region within an account's data area.
/// All fields are const-evaluable.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct StaticSegment {
    /// Field name (compile-time string).
    pub name: &'static str,
    /// Byte offset from the start of the layout body (after header).
    pub offset: u32,
    /// Byte size of this segment.
    pub size: u32,
}

impl StaticSegment {
    /// Construct a new static segment descriptor.
    #[inline(always)]
    pub const fn new(name: &'static str, offset: u32, size: u32) -> Self {
        Self { name, offset, size }
    }

    /// Byte offset past the end of this segment.
    #[inline(always)]
    pub const fn end(&self) -> u32 {
        self.offset + self.size
    }
}

/// Compile-time segment layout for a zero-copy struct.
///
/// Types implementing this trait declare their byte-level field map
/// as a constant array. This enables segment-level access with
/// zero runtime overhead — the compiler can resolve segment offsets
/// to immediate constants in the generated code.
///
/// ## Runtime vs Compile-Time
///
/// - `SegmentMap` = compile-time, generated from struct definitions
/// - `SegmentRegistry` = runtime, stored on-chain for dynamic accounts
///
/// Both can coexist: a struct might implement `SegmentMap` for its fixed
/// fields while also using `SegmentRegistry` for its dynamic segments.
pub trait SegmentMap {
    /// All segments in this layout, ordered by offset.
    const SEGMENTS: &'static [StaticSegment];

    /// Look up a segment by field name.
    ///
    /// Linear scan over const array. For layouts with ≤16 fields (the norm),
    /// this compiles to a small branchless sequence.
    #[inline]
    fn segment(name: &str) -> Option<StaticSegment> {
        let mut i = 0;
        while i < Self::SEGMENTS.len() {
            let seg = Self::SEGMENTS[i];
            if const_str_eq(seg.name, name) {
                return Some(seg);
            }
            i += 1;
        }
        None
    }

    /// Total size of the layout body (sum of all segments, or max(end)).
    #[inline]
    fn body_size() -> u32 {
        let segments = Self::SEGMENTS;
        if segments.is_empty() {
            return 0;
        }
        // Last segment end offset (assuming sorted by offset).
        let last = segments[segments.len() - 1];
        last.offset + last.size
    }

    /// Number of segments.
    #[inline(always)]
    fn segment_count() -> usize {
        Self::SEGMENTS.len()
    }
}

/// Constant string equality for segment name matching.
///
/// Works in const contexts. Used by the default `SegmentMap::segment()`.
#[inline(always)]
const fn const_str_eq(a: &str, b: &str) -> bool {
    let a = a.as_bytes();
    let b = b.as_bytes();
    if a.len() != b.len() {
        return false;
    }
    let mut i = 0;
    while i < a.len() {
        if a[i] != b[i] {
            return false;
        }
        i += 1;
    }
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    struct TestLayout;

    impl SegmentMap for TestLayout {
        const SEGMENTS: &'static [StaticSegment] = &[
            StaticSegment::new("authority", 0, 32),
            StaticSegment::new("balance", 32, 8),
            StaticSegment::new("bump", 40, 1),
        ];
    }

    #[test]
    fn lookup_by_name() {
        let seg = TestLayout::segment("balance").unwrap();
        assert_eq!(seg.offset, 32);
        assert_eq!(seg.size, 8);
    }

    #[test]
    fn lookup_missing() {
        assert!(TestLayout::segment("nonexistent").is_none());
    }

    #[test]
    fn body_size_computed() {
        assert_eq!(TestLayout::body_size(), 41);
    }

    #[test]
    fn segment_count() {
        assert_eq!(TestLayout::segment_count(), 3);
    }

    #[test]
    fn segment_end() {
        let seg = TestLayout::segment("authority").unwrap();
        assert_eq!(seg.end(), 32);
    }
}
