// Auto-generated by `hopper compile --emit rust-client`
// Program: hopper-lang v0.5.0
// DO NOT EDIT

//! Off-chain Rust client for the `hopper-lang` Hopper program.
//!
//! Every account decoder calls `assert_{name}_layout` first. Headered
//! accounts compare the on-chain `LAYOUT_ID`; compact accounts compare
//! exact size and discriminator. A mismatch is rejected before reading
//! stale bytes as if they were the new layout. This is the
//! client-side complement to the runtime's header check.

use solana_program::instruction::{AccountMeta, Instruction};
use solana_program::pubkey::Pubkey;

/// Hopper account-header size (bytes).
pub const HOPPER_HEADER_SIZE: usize = 16;
/// Byte offset of the 8-byte `LAYOUT_ID` fingerprint in a Hopper header.
pub const LAYOUT_ID_OFFSET: usize = 4;
/// Byte length of the fingerprint (always 8).
pub const LAYOUT_ID_LENGTH: usize = 8;

/// Shared error type for every decoder in this module.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ClientError {
    /// Buffer smaller than the bytes required by the selected decoder.
    BufferTooSmall { need: usize, got: usize },
    /// Account header's `LAYOUT_ID` does not match the layout the client
    /// was generated against. The on-chain ABI drifted from this client.
    LayoutMismatch { expected: [u8; 8], actual: [u8; 8] },
    /// Compact account length differs from the manifest's exact size.
    AccountSizeMismatch { expected: usize, actual: usize },
    /// Compact account discriminator differs from the manifest.
    DiscriminatorMismatch { expected: u8, actual: u8 },
    /// Event tag byte does not match the expected event decoder.
    EventTagMismatch { expected: u8, actual: u8 },
    /// Instruction discriminator byte does not match the expected builder/decoder.
    InstructionTagMismatch { expected: u8, actual: u8 },
}

impl core::fmt::Display for ClientError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::BufferTooSmall { need, got } => {
                write!(f, "hopper client: account too small, need {} bytes got {}", need, got)
            }
            Self::LayoutMismatch { expected, actual } => {
                write!(f, "hopper client: layout mismatch: expected {:02x?}, got {:02x?}", expected, actual)
            }
            Self::AccountSizeMismatch { expected, actual } => {
                write!(f, "hopper client: compact account size mismatch: expected {} got {}", expected, actual)
            }
            Self::DiscriminatorMismatch { expected, actual } => {
                write!(f, "hopper client: compact account discriminator mismatch: expected {} got {}", expected, actual)
            }
            Self::EventTagMismatch { expected, actual } => {
                write!(f, "hopper client: event tag mismatch: expected {} got {}", expected, actual)
            }
            Self::InstructionTagMismatch { expected, actual } => {
                write!(f, "hopper client: instruction tag mismatch: expected {} got {}", expected, actual)
            }
        }
    }
}

// Submit instruction (discriminator = 0)
pub const SUBMIT_DISC: u8 = 0;
pub const SUBMIT_DATA_LEN: usize = 15;

/// Arguments for the `submit` instruction.
#[derive(Clone, Debug)]
pub struct SubmitArgs {
    pub order: [u8; 12],
    pub nonce: u16,
}

/// Encode only the `submit` instruction data bytes.
pub fn encode_submit_data(args: &SubmitArgs) -> Vec<u8> {
    let mut data = Vec::with_capacity(SUBMIT_DATA_LEN);
    data.push(SUBMIT_DISC);
    data.extend_from_slice(args.order.as_ref());
    data.extend_from_slice(&args.nonce.to_le_bytes());
    data
}

/// Decode `submit` instruction data bytes into typed args.
pub fn decode_submit_args(data: &[u8]) -> Result<SubmitArgs, ClientError> {
    if data.len() < SUBMIT_DATA_LEN {
        return Err(ClientError::BufferTooSmall { need: SUBMIT_DATA_LEN, got: data.len() });
    }
    if data[0] != SUBMIT_DISC {
        return Err(ClientError::InstructionTagMismatch { expected: SUBMIT_DISC, actual: data[0] });
    }
    let order = {
        let mut buf = [0u8; 12];
        buf.copy_from_slice(&data[1..13]);
        buf
    };
    let nonce = {
        u16::from_le_bytes([data[13], data[14]])
    };
    Ok(SubmitArgs {
        order,
        nonce,
    })
}

/// Account keys for the `submit` instruction, in the order Hopper expects.
#[derive(Clone, Debug)]
pub struct SubmitAccounts {
    pub authority: Pubkey,
}

/// Build a `submit` transaction instruction.
///
/// The returned `Instruction` carries the exact `AccountMeta` order
/// and discriminator byte Hopper's runtime dispatcher expects.
pub fn submit_ix(
    program_id: &Pubkey,
    accounts: &SubmitAccounts,
    args: &SubmitArgs,
) -> Instruction {
    let data = encode_submit_data(args);
    let account_metas = vec![
        AccountMeta::new_readonly(accounts.authority, true),
    ];
    Instruction {
        program_id: *program_id,
        accounts: account_metas,
        data,
    }
}

// Empty instruction (discriminator = 1)
pub const EMPTY_DISC: u8 = 1;
pub const EMPTY_DATA_LEN: usize = 3;

/// Arguments for the `empty` instruction.
#[derive(Clone, Debug)]
pub struct EmptyArgs {
    pub empty: [u8; 0],
    pub nonce: u16,
}

/// Encode only the `empty` instruction data bytes.
pub fn encode_empty_data(args: &EmptyArgs) -> Vec<u8> {
    let mut data = Vec::with_capacity(EMPTY_DATA_LEN);
    data.push(EMPTY_DISC);
    data.extend_from_slice(args.empty.as_ref());
    data.extend_from_slice(&args.nonce.to_le_bytes());
    data
}

/// Decode `empty` instruction data bytes into typed args.
pub fn decode_empty_args(data: &[u8]) -> Result<EmptyArgs, ClientError> {
    if data.len() < EMPTY_DATA_LEN {
        return Err(ClientError::BufferTooSmall { need: EMPTY_DATA_LEN, got: data.len() });
    }
    if data[0] != EMPTY_DISC {
        return Err(ClientError::InstructionTagMismatch { expected: EMPTY_DISC, actual: data[0] });
    }
    let empty = {
        let mut buf = [0u8; 0];
        buf.copy_from_slice(&data[1..1]);
        buf
    };
    let nonce = {
        u16::from_le_bytes([data[1], data[2]])
    };
    Ok(EmptyArgs {
        empty,
        nonce,
    })
}

/// Account keys for the `empty` instruction, in the order Hopper expects.
#[derive(Clone, Debug)]
pub struct EmptyAccounts {
    pub authority: Pubkey,
}

/// Build a `empty` transaction instruction.
///
/// The returned `Instruction` carries the exact `AccountMeta` order
/// and discriminator byte Hopper's runtime dispatcher expects.
pub fn empty_ix(
    program_id: &Pubkey,
    accounts: &EmptyAccounts,
    args: &EmptyArgs,
) -> Instruction {
    let data = encode_empty_data(args);
    let account_metas = vec![
        AccountMeta::new_readonly(accounts.authority, true),
    ];
    Instruction {
        program_id: *program_id,
        accounts: account_metas,
        data,
    }
}

