// Auto-generated by hopper client gen --ts
// Program: hopper-lang v0.5.0
// DO NOT EDIT

import { AccountMeta, PublicKey, TransactionInstruction } from "@solana/web3.js";

export interface SubmitArgs {
  order: Uint8Array;
  nonce: number;
}

export interface SubmitAccounts {
  authority: PublicKey;
}

export function createSubmitInstruction(
  args: SubmitArgs,
  accounts: SubmitAccounts,
  programId: PublicKey,
): TransactionInstruction {
  if (args.order.length !== 12) throw new Error("order must encode exactly 12 bytes");
  const data = new Uint8Array(15);
  const view = new DataView(data.buffer);
  data[0] = 0; // instruction discriminator
  data.set(args.order, 1);
  view.setUint16(13, args.nonce, true);

  const keys = [
    { pubkey: accounts.authority, isSigner: true, isWritable: false },
  ];

  return new TransactionInstruction({ keys, programId, data });
}

export interface EmptyArgs {
  empty: Uint8Array;
  nonce: number;
}

export interface EmptyAccounts {
  authority: PublicKey;
}

export function createEmptyInstruction(
  args: EmptyArgs,
  accounts: EmptyAccounts,
  programId: PublicKey,
): TransactionInstruction {
  if (args.empty.length !== 0) throw new Error("empty must encode exactly 0 bytes");
  const data = new Uint8Array(3);
  const view = new DataView(data.buffer);
  data[0] = 1; // instruction discriminator
  data.set(args.empty, 1);
  view.setUint16(1, args.nonce, true);

  const keys = [
    { pubkey: accounts.authority, isSigner: true, isWritable: false },
  ];

  return new TransactionInstruction({ keys, programId, data });
}

