// Auto-generated by `hopper compile --emit rust-client`
// Program: hopper-lang v0.5.0
// DO NOT EDIT

//! Off-chain Rust client for the `hopper-lang` Hopper program.
//!
//! Every account decoder calls `assert_{name}_layout` first. Headered
//! accounts compare the on-chain `LAYOUT_ID`; compact accounts compare
//! exact size and discriminator. A mismatch is rejected before reading
//! stale bytes as if they were the new layout. This is the
//! client-side complement to the runtime's header check.

use solana_program::instruction::{AccountMeta, Instruction};
use solana_program::pubkey::Pubkey;

/// Hopper account-header size (bytes).
pub const HOPPER_HEADER_SIZE: usize = 16;
/// Byte offset of the 8-byte `LAYOUT_ID` fingerprint in a Hopper header.
pub const LAYOUT_ID_OFFSET: usize = 4;
/// Byte length of the fingerprint (always 8).
pub const LAYOUT_ID_LENGTH: usize = 8;

/// Shared error type for every decoder in this module.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ClientError {
    /// Invalid length, UTF-8, or bounded instruction argument.
    InvalidInstructionData,
    /// Buffer smaller than the bytes required by the selected decoder.
    BufferTooSmall { need: usize, got: usize },
    /// Account header's `LAYOUT_ID` does not match the layout the client
    /// was generated against. The on-chain ABI drifted from this client.
    LayoutMismatch { expected: [u8; 8], actual: [u8; 8] },
    /// Compact account length differs from the manifest's exact size.
    AccountSizeMismatch { expected: usize, actual: usize },
    /// Compact account discriminator differs from the manifest.
    DiscriminatorMismatch { expected: u8, actual: u8 },
    /// Event tag byte does not match the expected event decoder.
    EventTagMismatch { expected: u8, actual: u8 },
    /// Instruction discriminator byte does not match the expected builder/decoder.
    InstructionTagMismatch { expected: u8, actual: u8 },
}

impl core::fmt::Display for ClientError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::InvalidInstructionData => write!(f, "hopper client: invalid instruction data"),
            Self::BufferTooSmall { need, got } => {
                write!(f, "hopper client: account too small, need {} bytes got {}", need, got)
            }
            Self::LayoutMismatch { expected, actual } => {
                write!(f, "hopper client: layout mismatch: expected {:02x?}, got {:02x?}", expected, actual)
            }
            Self::AccountSizeMismatch { expected, actual } => {
                write!(f, "hopper client: compact account size mismatch: expected {} got {}", expected, actual)
            }
            Self::DiscriminatorMismatch { expected, actual } => {
                write!(f, "hopper client: compact account discriminator mismatch: expected {} got {}", expected, actual)
            }
            Self::EventTagMismatch { expected, actual } => {
                write!(f, "hopper client: event tag mismatch: expected {} got {}", expected, actual)
            }
            Self::InstructionTagMismatch { expected, actual } => {
                write!(f, "hopper client: instruction tag mismatch: expected {} got {}", expected, actual)
            }
        }
    }
}

// Submit instruction (discriminator = 0)
pub const SUBMIT_DISC: u8 = 0;
/// Maximum encoded byte length; actual batches may be shorter.
pub const SUBMIT_DATA_LEN: usize = 45;

/// Arguments for the `submit` instruction.
#[derive(Clone, Debug)]
pub struct SubmitArgs {
    pub orders: Vec<[u8; 10]>,
    pub nonce: u16,
}

/// Encode bounded arguments; refuse excessive counts or byte lengths.
pub fn encode_submit_data(args: &SubmitArgs) -> Result<Vec<u8>, ClientError> {
    if args.orders.len() > 4 { return Err(ClientError::InvalidInstructionData); }
    let mut data = Vec::new();
    data.push(SUBMIT_DISC);
    data.extend_from_slice(&(args.orders.len() as u16).to_le_bytes());
    for value in &args.orders { data.extend_from_slice(value); }
    data.extend_from_slice(&args.nonce.to_le_bytes());
    Ok(data)
}

/// Decode the complete instruction; sequence elements remain wire bytes.
pub fn decode_submit_args(data: &[u8]) -> Result<SubmitArgs, ClientError> {
    let tag = *data.first().ok_or(ClientError::BufferTooSmall { need: 1, got: 0 })?;
    if tag != SUBMIT_DISC { return Err(ClientError::InstructionTagMismatch { expected: SUBMIT_DISC, actual: tag }); }
    let mut offset = 1usize;
    let orders = {
        let prefix_end = offset.checked_add(2).ok_or(ClientError::InvalidInstructionData)?;
        let prefix = data.get(offset..prefix_end).ok_or(ClientError::BufferTooSmall { need: prefix_end, got: data.len() })?;
        let count = u16::from_le_bytes([prefix[0], prefix[1]]) as usize;
        if count > 4 { return Err(ClientError::InvalidInstructionData); }
        let size = count.checked_mul(10).ok_or(ClientError::InvalidInstructionData)?;
        let end = prefix_end.checked_add(size).ok_or(ClientError::InvalidInstructionData)?;
        let bytes = data.get(prefix_end..end).ok_or(ClientError::BufferTooSmall { need: end, got: data.len() })?;
        offset = end;
        let mut values = Vec::with_capacity(count);
        for chunk in bytes.chunks_exact(10) {
            let mut value = [0u8; 10]; value.copy_from_slice(chunk); values.push(value);
        }
        values
    };
    let nonce = {
        let end = offset.checked_add(2).ok_or(ClientError::InvalidInstructionData)?;
        let data = data.get(offset..end).ok_or(ClientError::BufferTooSmall { need: end, got: data.len() })?;
        offset = end;
        u16::from_le_bytes([data[0], data[1]])
    };
    if offset != data.len() { return Err(ClientError::InvalidInstructionData); }
    Ok(SubmitArgs {
        orders,
        nonce,
    })
}

/// Account keys for the `submit` instruction, in the order Hopper expects.
#[derive(Clone, Debug)]
pub struct SubmitAccounts {
    pub authority: Pubkey,
}

/// Build a `submit` transaction instruction.
///
/// The returned `Instruction` carries the exact `AccountMeta` order
/// and discriminator byte Hopper's runtime dispatcher expects.
pub fn submit_ix(
    program_id: &Pubkey,
    accounts: &SubmitAccounts,
    args: &SubmitArgs,
) -> Result<Instruction, ClientError> {
    let data = encode_submit_data(args)?;
    let account_metas = vec![
        AccountMeta::new_readonly(accounts.authority, true),
    ];
    Ok(Instruction {
        program_id: *program_id,
        accounts: account_metas,
        data,
    })
}

// Bytes instruction (discriminator = 1)
pub const BYTES_DISC: u8 = 1;
/// Maximum encoded byte length; actual batches may be shorter.
pub const BYTES_DATA_LEN: usize = 29;

/// Arguments for the `bytes` instruction.
#[derive(Clone, Debug)]
pub struct BytesArgs {
    pub bytes: Vec<[u8; 1]>,
    pub note: String,
}

/// Encode bounded arguments; refuse excessive counts or byte lengths.
pub fn encode_bytes_data(args: &BytesArgs) -> Result<Vec<u8>, ClientError> {
    if args.bytes.len() > 8 { return Err(ClientError::InvalidInstructionData); }
    if args.note.len() > 16 { return Err(ClientError::InvalidInstructionData); }
    let mut data = Vec::new();
    data.push(BYTES_DISC);
    data.extend_from_slice(&(args.bytes.len() as u16).to_le_bytes());
    for value in &args.bytes { data.extend_from_slice(value); }
    data.extend_from_slice(&(args.note.len() as u16).to_le_bytes());
    data.extend_from_slice(args.note.as_bytes());
    Ok(data)
}

/// Decode the complete instruction; sequence elements remain wire bytes.
pub fn decode_bytes_args(data: &[u8]) -> Result<BytesArgs, ClientError> {
    let tag = *data.first().ok_or(ClientError::BufferTooSmall { need: 1, got: 0 })?;
    if tag != BYTES_DISC { return Err(ClientError::InstructionTagMismatch { expected: BYTES_DISC, actual: tag }); }
    let mut offset = 1usize;
    let bytes = {
        let prefix_end = offset.checked_add(2).ok_or(ClientError::InvalidInstructionData)?;
        let prefix = data.get(offset..prefix_end).ok_or(ClientError::BufferTooSmall { need: prefix_end, got: data.len() })?;
        let count = u16::from_le_bytes([prefix[0], prefix[1]]) as usize;
        if count > 8 { return Err(ClientError::InvalidInstructionData); }
        let size = count.checked_mul(1).ok_or(ClientError::InvalidInstructionData)?;
        let end = prefix_end.checked_add(size).ok_or(ClientError::InvalidInstructionData)?;
        let bytes = data.get(prefix_end..end).ok_or(ClientError::BufferTooSmall { need: end, got: data.len() })?;
        offset = end;
        let mut values = Vec::with_capacity(count);
        for chunk in bytes.chunks_exact(1) {
            let mut value = [0u8; 1]; value.copy_from_slice(chunk); values.push(value);
        }
        values
    };
    let note = {
        let prefix_end = offset.checked_add(2).ok_or(ClientError::InvalidInstructionData)?;
        let prefix = data.get(offset..prefix_end).ok_or(ClientError::BufferTooSmall { need: prefix_end, got: data.len() })?;
        let count = u16::from_le_bytes([prefix[0], prefix[1]]) as usize;
        if count > 16 { return Err(ClientError::InvalidInstructionData); }
        let size = count.checked_mul(1).ok_or(ClientError::InvalidInstructionData)?;
        let end = prefix_end.checked_add(size).ok_or(ClientError::InvalidInstructionData)?;
        let bytes = data.get(prefix_end..end).ok_or(ClientError::BufferTooSmall { need: end, got: data.len() })?;
        offset = end;
        core::str::from_utf8(bytes).map_err(|_| ClientError::InvalidInstructionData)?.to_owned()
    };
    if offset != data.len() { return Err(ClientError::InvalidInstructionData); }
    Ok(BytesArgs {
        bytes,
        note,
    })
}

/// Account keys for the `bytes` instruction, in the order Hopper expects.
#[derive(Clone, Debug)]
pub struct BytesAccounts {
    pub authority: Pubkey,
}

/// Build a `bytes` transaction instruction.
///
/// The returned `Instruction` carries the exact `AccountMeta` order
/// and discriminator byte Hopper's runtime dispatcher expects.
pub fn bytes_ix(
    program_id: &Pubkey,
    accounts: &BytesAccounts,
    args: &BytesArgs,
) -> Result<Instruction, ClientError> {
    let data = encode_bytes_data(args)?;
    let account_metas = vec![
        AccountMeta::new_readonly(accounts.authority, true),
    ];
    Ok(Instruction {
        program_id: *program_id,
        accounts: account_metas,
        data,
    })
}

