// Auto-generated by hopper client gen --ts
// Program: hopper-lang v0.5.0
// DO NOT EDIT

import { AccountMeta, PublicKey, TransactionInstruction } from "@solana/web3.js";

export interface SubmitArgs {
  orders: readonly Uint8Array[];
  nonce: number;
}

export interface SubmitAccounts {
  authority: PublicKey;
}

export function createSubmitInstruction(
  args: SubmitArgs,
  accounts: SubmitAccounts,
  programId: PublicKey,
): TransactionInstruction {
  if (args.orders.length > 4) throw new Error("orders exceeds its bounded capacity of 4");
  for (const value of args.orders) {
    if (value.length !== 10) throw new Error("orders element has the wrong encoded size");
  }
  const data = new Uint8Array(1 + 2 + args.orders.length * 10 + 2);
  const view = new DataView(data.buffer);
  data[0] = 0; // instruction discriminator
  let offset = 1;
  view.setUint16(offset, args.orders.length, true);
  offset += 2;
  for (const value of args.orders) {
    data.set(value, offset);
    offset += 10;
  }
  view.setUint16(offset, args.nonce, true);
  offset += 2;

  const keys = [
    { pubkey: accounts.authority, isSigner: true, isWritable: false },
  ];

  return new TransactionInstruction({ keys, programId, data });
}

export interface BytesArgs {
  bytes: Uint8Array;
  note: string;
}

export interface BytesAccounts {
  authority: PublicKey;
}

export function createBytesInstruction(
  args: BytesArgs,
  accounts: BytesAccounts,
  programId: PublicKey,
): TransactionInstruction {
  if (args.bytes.length > 8) throw new Error("bytes exceeds its bounded capacity of 8");
  const noteBytes = new TextEncoder().encode(args.note);
  if (noteBytes.length > 16) throw new Error("note exceeds its bounded UTF-8 capacity of 16 bytes");
  const data = new Uint8Array(1 + 2 + args.bytes.length * 1 + 2 + noteBytes.length);
  const view = new DataView(data.buffer);
  data[0] = 1; // instruction discriminator
  let offset = 1;
  view.setUint16(offset, args.bytes.length, true);
  offset += 2;
  data.set(args.bytes, offset);
  offset += args.bytes.length;
  view.setUint16(offset, noteBytes.length, true);
  offset += 2;
  data.set(noteBytes, offset);
  offset += noteBytes.length;

  const keys = [
    { pubkey: accounts.authority, isSigner: true, isWritable: false },
  ];

  return new TransactionInstruction({ keys, programId, data });
}

