#!/usr/bin/env python3
"""Reject unsafe blocks without nearby SAFETY comments and pub unsafe fns without docs.

This intentionally uses a lightweight textual scan rather than a Rust parser so
it can run in CI without installing extra tooling. It is scoped to the Hopper
crates that host audited unsafe boundaries.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys

ROOTS = [
    Path("crates/hopper-native/src"),
    Path("crates/hopper-runtime/src"),
    Path("crates/hopper-solana/src"),
    Path("crates/hopper-core/src"),
]

UNSAFE_BLOCK = re.compile(r"\bunsafe\s*\{")
PUB_UNSAFE_FN = re.compile(r"\bpub\s+unsafe\s+fn\b")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Check unsafe safety comments and optionally emit an inventory markdown file."
    )
    parser.add_argument(
        "--inventory-out",
        type=Path,
        help="Write a markdown inventory of unsafe blocks and public unsafe functions.",
    )
    return parser.parse_args()


def is_doc_or_comment(line: str) -> bool:
    stripped = line.lstrip()
    return stripped.startswith("///") or stripped.startswith("//!")


def nearby_safety(lines: list[str], index: int, radius: int = 3) -> bool:
    # Inline window: a `// SAFETY:` on the same line or within `radius` lines
    # after the block (covers trailing-comment styles).
    start = max(0, index - radius)
    end = min(len(lines), index + radius + 1)
    if any("SAFETY:" in lines[i] for i in range(start, end)):
        return True
    # Attached-comment-block scan: walk up through the contiguous run of
    # comment / attribute / blank lines immediately above the `unsafe` block
    # and accept if any carries a `SAFETY:` tag. This rewards thorough
    # multi-line SAFETY invariants (which can exceed the fixed radius) while
    # still requiring the comment to be attached to the block rather than
    # floating elsewhere in the file.
    cursor = index - 1
    while cursor >= 0:
        stripped = lines[cursor].rstrip()
        lstripped = stripped.lstrip()
        if lstripped.startswith("//") or lstripped.startswith("#[") or lstripped == "":
            if "SAFETY:" in lines[cursor]:
                return True
            cursor -= 1
            continue
        # Step over an assignment-continuation line: rustfmt breaks a long
        # `let x: LongType =\n    unsafe { ... }` binding, so the SAFETY
        # comment documenting the statement sits above the `let`, one line
        # further up than the `unsafe` token. The `=` suffix is the reliable
        # marker of exactly this split.
        if stripped.endswith("="):
            cursor -= 1
            continue
        break
    return False


def doc_block_has_safety(lines: list[str], index: int) -> bool:
    seen: list[str] = []
    cursor = index - 1
    while cursor >= 0:
        stripped = lines[cursor].lstrip()
        if (
            stripped.startswith("///")
            or stripped.startswith("#[")
            or stripped == ""
            or stripped.startswith("//")
        ):
            seen.append(lines[cursor])
            cursor -= 1
            continue
        break
    return "# Safety" in "\n".join(reversed(seen))


def write_inventory(path: Path, inventory: list[tuple[Path, int, int]], checked_files: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Unsafe inventory",
        "",
        "Generated by `scripts/check-unsafe-safety-comments.py`.",
        "",
        f"Checked Rust files: {checked_files}",
        "",
        "| Source file | Unsafe blocks | Public unsafe functions |",
        "| --- | ---: | ---: |",
    ]
    if inventory:
        for source, unsafe_blocks, public_unsafe_fns in inventory:
            lines.append(f"| `{source.as_posix()}` | {unsafe_blocks} | {public_unsafe_fns} |")
    else:
        lines.append("| _none_ | 0 | 0 |")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    args = parse_args()
    failures: list[str] = []
    inventory: list[tuple[Path, int, int]] = []
    files = sorted({path for root in ROOTS for path in root.rglob("*.rs")})
    for path in files:
        lines = path.read_text(encoding="utf-8").splitlines()
        unsafe_blocks = 0
        public_unsafe_fns = 0
        for idx, line in enumerate(lines):
            if is_doc_or_comment(line):
                continue
            if UNSAFE_BLOCK.search(line):
                unsafe_blocks += 1
                if not nearby_safety(lines, idx):
                    failures.append(f"{path}:{idx + 1}: unsafe block lacks nearby SAFETY comment")
            if PUB_UNSAFE_FN.search(line):
                public_unsafe_fns += 1
                if not doc_block_has_safety(lines, idx):
                    failures.append(f"{path}:{idx + 1}: pub unsafe fn lacks rustdoc # Safety section")
        if unsafe_blocks or public_unsafe_fns:
            inventory.append((path, unsafe_blocks, public_unsafe_fns))

    if args.inventory_out:
        write_inventory(args.inventory_out, inventory, len(files))

    if failures:
        print("Unsafe safety-comment check failed:", file=sys.stderr)
        for failure in failures:
            print(f"  {failure}", file=sys.stderr)
        return 1
    print(f"checked {len(files)} Rust files for unsafe SAFETY comments")
    if args.inventory_out:
        print(f"wrote unsafe inventory to {args.inventory_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())