[package]
name = "hopper-counter"
version = "0.3.0"
edition = "2021"
license = "Apache-2.0"
publish = false
description = "Minimal macro-first Hopper counter example."

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
hopper = { workspace = true, features = ["proc-macros"] }

[lints]
workspace = true