[package]
name = "hopper-escrow"
version = "0.3.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
hopper = { path = "../..", package = "hopper-lang", default-features = false, features = ["proc-macros"] }

[dev-dependencies]
solana-client = "=4.2.1"
solana-keypair = "=3.1.2"
solana-pubkey = "=4.2.1"
solana-signer = "=3.0.1"
solana-instruction = "=3.4.0"
solana-transaction = { version = "=4.1.4", features = ["serde", "wincode"] }
solana-system-interface = { version = "=3.2.0", features = ["bincode"] }
solana-commitment-config = "=3.1.1"

[features]
default = []

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(target_os, values("solana"))'] }
