//! C client generator.
//!
//! Emits a single header-style C client from a [`ProgramManifest`]. The output
//! is dependency-light and transport-agnostic: callers get typed account
//! decoders, event decoders, account metadata arrays, and discriminator-prefixed
//! instruction data builders.

extern crate alloc;

use alloc::{format, string::String};
use core::fmt;

use crate::{
    EventDescriptor, FieldDescriptor, InstructionDescriptor, LayoutManifest, ProgramManifest,
};

/// Full C client emitter.
pub struct CClientGen<'a>(pub &'a ProgramManifest);

impl<'a> fmt::Display for CClientGen<'a> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let prog = self.0;
        let guard = format!("HOPPER_{}_CLIENT_H", upper_snake_case(prog.name));

        writeln!(
            f,
            "/* Auto-generated by `hopper compile --emit c`. DO NOT EDIT. */"
        )?;
        writeln!(f, "/* Program: {} v{} */", prog.name, prog.version)?;
        writeln!(f, "#ifndef {}", guard)?;
        writeln!(f, "#define {}", guard)?;
        writeln!(f)?;
        writeln!(f, "#include <stdbool.h>")?;
        writeln!(f, "#include <stddef.h>")?;
        writeln!(f, "#include <stdint.h>")?;
        writeln!(f, "#include <string.h>")?;
        writeln!(f)?;
        writeln!(f, "#define HOPPER_HEADER_SIZE 16u")?;
        writeln!(f, "#define HOPPER_LAYOUT_ID_OFFSET 4u")?;
        writeln!(f, "#define HOPPER_LAYOUT_ID_LENGTH 8u")?;
        writeln!(f)?;
        writeln!(f, "typedef struct {{ uint8_t bytes[32]; }} HopperPubkey;")?;
        writeln!(f, "typedef struct {{ HopperPubkey pubkey; bool is_signer; bool is_writable; const char *layout; }} HopperAccountMeta;")?;
        writeln!(f)?;
        writeln!(f, "typedef enum {{")?;
        writeln!(f, "    HOPPER_CLIENT_OK = 0,")?;
        writeln!(f, "    HOPPER_CLIENT_BUFFER_TOO_SMALL = 1,")?;
        writeln!(f, "    HOPPER_CLIENT_LAYOUT_MISMATCH = 2,")?;
        writeln!(f, "    HOPPER_CLIENT_TAG_MISMATCH = 3")?;
        writeln!(f, "}} HopperClientError;")?;
        writeln!(f)?;
        write_helpers(f)?;

        for layout in prog.layouts.iter() {
            write_layout(f, layout)?;
        }
        for ix in prog.instructions.iter() {
            write_instruction(f, ix)?;
        }
        for event in prog.events.iter() {
            write_event(f, event)?;
        }

        writeln!(f, "#endif /* {} */", guard)?;
        Ok(())
    }
}

fn write_helpers(f: &mut fmt::Formatter<'_>) -> fmt::Result {
    writeln!(
        f,
        "static inline uint16_t hopper_read_le_u16(const uint8_t *p) {{"
    )?;
    writeln!(f, "    return (uint16_t)p[0] | ((uint16_t)p[1] << 8);")?;
    writeln!(f, "}}")?;
    writeln!(
        f,
        "static inline uint32_t hopper_read_le_u32(const uint8_t *p) {{"
    )?;
    writeln!(f, "    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);")?;
    writeln!(f, "}}")?;
    writeln!(
        f,
        "static inline uint64_t hopper_read_le_u64(const uint8_t *p) {{"
    )?;
    writeln!(f, "    uint64_t out = 0;")?;
    writeln!(
        f,
        "    for (size_t i = 0; i < 8; i++) out |= ((uint64_t)p[i]) << (8u * i);"
    )?;
    writeln!(f, "    return out;")?;
    writeln!(f, "}}")?;
    writeln!(
        f,
        "static inline void hopper_write_le_u16(uint8_t *p, uint16_t v) {{"
    )?;
    writeln!(
        f,
        "    p[0] = (uint8_t)(v & 0xffu); p[1] = (uint8_t)((v >> 8) & 0xffu);"
    )?;
    writeln!(f, "}}")?;
    writeln!(
        f,
        "static inline void hopper_write_le_u32(uint8_t *p, uint32_t v) {{"
    )?;
    writeln!(
        f,
        "    for (size_t i = 0; i < 4; i++) p[i] = (uint8_t)((v >> (8u * i)) & 0xffu);"
    )?;
    writeln!(f, "}}")?;
    writeln!(
        f,
        "static inline void hopper_write_le_u64(uint8_t *p, uint64_t v) {{"
    )?;
    writeln!(
        f,
        "    for (size_t i = 0; i < 8; i++) p[i] = (uint8_t)((v >> (8u * i)) & 0xffu);"
    )?;
    writeln!(f, "}}")?;
    writeln!(f, "static inline HopperClientError hopper_assert_layout_id(const uint8_t *data, size_t data_len, const uint8_t expected[8]) {{")?;
    writeln!(
        f,
        "    if (data_len < HOPPER_HEADER_SIZE) return HOPPER_CLIENT_BUFFER_TOO_SMALL;"
    )?;
    writeln!(f, "    return memcmp(data + HOPPER_LAYOUT_ID_OFFSET, expected, HOPPER_LAYOUT_ID_LENGTH) == 0 ? HOPPER_CLIENT_OK : HOPPER_CLIENT_LAYOUT_MISMATCH;")?;
    writeln!(f, "}}")?;
    writeln!(f)?;
    Ok(())
}

fn write_layout(f: &mut fmt::Formatter<'_>, layout: &LayoutManifest) -> fmt::Result {
    let snake = snake_case(layout.name);
    let upper = upper_snake_case(layout.name);

    writeln!(f, "#define HOPPER_{}_DISC {}u", upper, layout.disc)?;
    writeln!(f, "#define HOPPER_{}_VERSION {}u", upper, layout.version)?;
    writeln!(
        f,
        "#define HOPPER_{}_TOTAL_SIZE {}u",
        upper, layout.total_size
    )?;
    write!(f, "static const uint8_t HOPPER_{}_LAYOUT_ID[8] = {{", upper)?;
    write_byte_list(f, &layout.layout_id)?;
    writeln!(f, "}};")?;
    writeln!(f)?;

    writeln!(f, "typedef struct {{")?;
    for field in layout.fields.iter() {
        write_c_decl(f, field, &snake_case(field.name))?;
    }
    writeln!(f, "}} Hopper{};", pascal_case(layout.name))?;
    writeln!(f)?;

    writeln!(f, "static inline HopperClientError hopper_assert_{}_layout(const uint8_t *data, size_t data_len) {{", snake)?;
    writeln!(
        f,
        "    return hopper_assert_layout_id(data, data_len, HOPPER_{}_LAYOUT_ID);",
        upper
    )?;
    writeln!(f, "}}")?;
    writeln!(f)?;

    writeln!(f, "static inline HopperClientError hopper_decode_{}(const uint8_t *data, size_t data_len, Hopper{} *out) {{", snake, pascal_case(layout.name))?;
    writeln!(
        f,
        "    HopperClientError err = hopper_assert_{}_layout(data, data_len);",
        snake
    )?;
    writeln!(f, "    if (err != HOPPER_CLIENT_OK) return err;")?;
    writeln!(
        f,
        "    if (data_len < HOPPER_{}_TOTAL_SIZE) return HOPPER_CLIENT_BUFFER_TOO_SMALL;",
        upper
    )?;
    for field in layout.fields.iter() {
        write_field_decode(f, field, "out->")?;
    }
    writeln!(f, "    return HOPPER_CLIENT_OK;")?;
    writeln!(f, "}}")?;
    writeln!(f)?;
    Ok(())
}

fn write_instruction(f: &mut fmt::Formatter<'_>, ix: &InstructionDescriptor) -> fmt::Result {
    let snake = snake_case(ix.name);
    let upper = upper_snake_case(ix.name);
    let pascal = pascal_case(ix.name);
    let data_len = 1usize + ix.args.iter().map(|arg| arg.size as usize).sum::<usize>();

    writeln!(f, "#define HOPPER_{}_DISC {}u", upper, ix.tag)?;
    writeln!(f, "#define HOPPER_{}_DATA_LEN {}u", upper, data_len)?;
    writeln!(
        f,
        "#define HOPPER_{}_ACCOUNT_COUNT {}u",
        upper,
        ix.accounts.len()
    )?;
    writeln!(f)?;

    if !ix.args.is_empty() {
        writeln!(f, "typedef struct {{")?;
        for arg in ix.args.iter() {
            let fd = FieldDescriptor {
                name: arg.name,
                canonical_type: arg.canonical_type,
                size: arg.size,
                offset: 0,
                intent: crate::FieldIntent::Custom,
            };
            write_c_decl(f, &fd, &snake_case(arg.name))?;
        }
        writeln!(f, "}} Hopper{}Args;", pascal)?;
        writeln!(f)?;
    }

    writeln!(f, "typedef struct {{")?;
    for account in ix.accounts.iter() {
        writeln!(f, "    HopperPubkey {};", snake_case(account.name))?;
    }
    writeln!(f, "}} Hopper{}Accounts;", pascal)?;
    writeln!(f)?;

    writeln!(f, "static inline size_t hopper_{}_account_metas(const Hopper{}Accounts *accounts, HopperAccountMeta out[HOPPER_{}_ACCOUNT_COUNT]) {{", snake, pascal, upper)?;
    for (i, account) in ix.accounts.iter().enumerate() {
        writeln!(
            f,
            "    out[{}].pubkey = accounts->{};",
            i,
            snake_case(account.name)
        )?;
        writeln!(f, "    out[{}].is_signer = {};", i, c_bool(account.signer))?;
        writeln!(
            f,
            "    out[{}].is_writable = {};",
            i,
            c_bool(account.writable)
        )?;
        writeln!(f, "    out[{}].layout = \"{}\";", i, account.layout_ref)?;
    }
    writeln!(f, "    return HOPPER_{}_ACCOUNT_COUNT;", upper)?;
    writeln!(f, "}}")?;
    writeln!(f)?;

    write!(
        f,
        "static inline HopperClientError hopper_build_{}_data(",
        snake
    )?;
    if !ix.args.is_empty() {
        write!(f, "const Hopper{}Args *args, ", pascal)?;
    }
    writeln!(f, "uint8_t *out, size_t out_len, size_t *written) {{")?;
    writeln!(
        f,
        "    if (out_len < HOPPER_{}_DATA_LEN) return HOPPER_CLIENT_BUFFER_TOO_SMALL;",
        upper
    )?;
    writeln!(f, "    out[0] = HOPPER_{}_DISC;", upper)?;
    let mut offset = 1usize;
    for arg in ix.args.iter() {
        write_arg_encode(
            f,
            arg.canonical_type,
            &format!("args->{}", snake_case(arg.name)),
            offset,
            arg.size as usize,
        )?;
        offset += arg.size as usize;
    }
    writeln!(
        f,
        "    if (written != NULL) *written = HOPPER_{}_DATA_LEN;",
        upper
    )?;
    writeln!(f, "    return HOPPER_CLIENT_OK;")?;
    writeln!(f, "}}")?;
    writeln!(f)?;
    Ok(())
}

fn write_event(f: &mut fmt::Formatter<'_>, event: &EventDescriptor) -> fmt::Result {
    let snake = snake_case(event.name);
    let upper = upper_snake_case(event.name);
    let pascal = pascal_case(event.name);
    let total_size = event_data_len(event);
    writeln!(f, "#define HOPPER_{}_EVENT_TAG {}u", upper, event.tag)?;
    writeln!(f, "#define HOPPER_{}_EVENT_DATA_LEN {}u", upper, total_size)?;
    writeln!(f, "typedef struct {{")?;
    for field in event.fields.iter() {
        write_c_decl(f, field, &snake_case(field.name))?;
    }
    writeln!(f, "}} Hopper{}Event;", pascal)?;
    writeln!(f)?;
    writeln!(f, "static inline HopperClientError hopper_decode_{}_event(const uint8_t *data, size_t data_len, Hopper{}Event *out) {{", snake, pascal)?;
    writeln!(
        f,
        "    if (data_len < HOPPER_{}_EVENT_DATA_LEN) return HOPPER_CLIENT_BUFFER_TOO_SMALL;",
        upper
    )?;
    writeln!(
        f,
        "    if (data[0] != HOPPER_{}_EVENT_TAG) return HOPPER_CLIENT_TAG_MISMATCH;",
        upper
    )?;
    for field in event.fields.iter() {
        write_event_field_decode(f, field, "out->")?;
    }
    writeln!(f, "    return HOPPER_CLIENT_OK;")?;
    writeln!(f, "}}")?;
    writeln!(f)?;
    Ok(())
}

fn write_field_decode(
    f: &mut fmt::Formatter<'_>,
    field: &FieldDescriptor,
    target_prefix: &str,
) -> fmt::Result {
    write_field_decode_at(f, field, target_prefix, field.offset as usize)
}

fn write_event_field_decode(
    f: &mut fmt::Formatter<'_>,
    field: &FieldDescriptor,
    target_prefix: &str,
) -> fmt::Result {
    write_field_decode_at(f, field, target_prefix, field.offset as usize + 1)
}

fn write_field_decode_at(
    f: &mut fmt::Formatter<'_>,
    field: &FieldDescriptor,
    target_prefix: &str,
    offset: usize,
) -> fmt::Result {
    let name = snake_case(field.name);
    let end = offset + field.size as usize;
    match field.canonical_type {
        "u8" => writeln!(f, "    {}{} = data[{}];", target_prefix, name, offset),
        "i8" => writeln!(
            f,
            "    {}{} = (int8_t)data[{}];",
            target_prefix, name, offset
        ),
        "u16" => writeln!(
            f,
            "    {}{} = hopper_read_le_u16(data + {});",
            target_prefix, name, offset
        ),
        "i16" => writeln!(
            f,
            "    {}{} = (int16_t)hopper_read_le_u16(data + {});",
            target_prefix, name, offset
        ),
        "u32" => writeln!(
            f,
            "    {}{} = hopper_read_le_u32(data + {});",
            target_prefix, name, offset
        ),
        "i32" => writeln!(
            f,
            "    {}{} = (int32_t)hopper_read_le_u32(data + {});",
            target_prefix, name, offset
        ),
        "u64" | "WireU64" => writeln!(
            f,
            "    {}{} = hopper_read_le_u64(data + {});",
            target_prefix, name, offset
        ),
        "i64" | "WireI64" => writeln!(
            f,
            "    {}{} = (int64_t)hopper_read_le_u64(data + {});",
            target_prefix, name, offset
        ),
        "bool" | "WireBool" => {
            writeln!(f, "    {}{} = data[{}] != 0;", target_prefix, name, offset)
        }
        "Pubkey" => writeln!(
            f,
            "    memcpy({}{}.bytes, data + {}, 32u);",
            target_prefix, name, offset
        ),
        _ => writeln!(
            f,
            "    memcpy({}{}, data + {}, {}u);",
            target_prefix,
            name,
            offset,
            end - offset
        ),
    }
}

fn write_arg_encode(
    f: &mut fmt::Formatter<'_>,
    canonical: &str,
    expr: &str,
    offset: usize,
    size: usize,
) -> fmt::Result {
    match canonical {
        "u8" => writeln!(f, "    out[{}] = {};", offset, expr),
        "i8" => writeln!(f, "    out[{}] = (uint8_t){};", offset, expr),
        "u16" => writeln!(f, "    hopper_write_le_u16(out + {}, {});", offset, expr),
        "i16" => writeln!(
            f,
            "    hopper_write_le_u16(out + {}, (uint16_t){});",
            offset, expr
        ),
        "u32" => writeln!(f, "    hopper_write_le_u32(out + {}, {});", offset, expr),
        "i32" => writeln!(
            f,
            "    hopper_write_le_u32(out + {}, (uint32_t){});",
            offset, expr
        ),
        "u64" | "WireU64" => writeln!(f, "    hopper_write_le_u64(out + {}, {});", offset, expr),
        "i64" | "WireI64" => writeln!(
            f,
            "    hopper_write_le_u64(out + {}, (uint64_t){});",
            offset, expr
        ),
        "bool" | "WireBool" => writeln!(f, "    out[{}] = {} ? 1u : 0u;", offset, expr),
        "Pubkey" => writeln!(f, "    memcpy(out + {}, {}.bytes, 32u);", offset, expr),
        _ => writeln!(f, "    memcpy(out + {}, {}, {}u);", offset, expr, size),
    }
}

fn c_type(field: &FieldDescriptor) -> String {
    match field.canonical_type {
        "u8" => "uint8_t".into(),
        "i8" => "int8_t".into(),
        "u16" => "uint16_t".into(),
        "i16" => "int16_t".into(),
        "u32" => "uint32_t".into(),
        "i32" => "int32_t".into(),
        "u64" | "WireU64" => "uint64_t".into(),
        "i64" | "WireI64" => "int64_t".into(),
        "bool" | "WireBool" => "bool".into(),
        "Pubkey" => "HopperPubkey".into(),
        _ => "uint8_t".into(),
    }
}

fn write_c_decl(f: &mut fmt::Formatter<'_>, field: &FieldDescriptor, name: &str) -> fmt::Result {
    match field.canonical_type {
        "u8" | "i8" | "u16" | "i16" | "u32" | "i32" | "u64" | "i64" | "WireU64" | "WireI64"
        | "bool" | "WireBool" | "Pubkey" => {
            writeln!(f, "    {} {};", c_type(field), name)
        }
        _ => writeln!(f, "    uint8_t {}[{}];", name, field.size),
    }
}

fn c_bool(value: bool) -> &'static str {
    if value {
        "true"
    } else {
        "false"
    }
}

fn pascal_case(s: &str) -> String {
    let mut out = String::new();
    let mut upper_next = true;
    for c in s.chars() {
        if c == '_' || c == '-' || c == ' ' {
            upper_next = true;
        } else if upper_next {
            out.extend(c.to_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn snake_case(s: &str) -> String {
    let mut out = String::new();
    let mut first = true;
    for c in s.chars() {
        if c == '_' || c == '-' || c == ' ' {
            if !out.ends_with('_') {
                out.push('_');
            }
        } else if c.is_uppercase() {
            if !first && !out.ends_with('_') {
                out.push('_');
            }
            out.extend(c.to_lowercase());
        } else {
            out.push(c);
        }
        first = false;
    }
    out
}

fn upper_snake_case(s: &str) -> String {
    snake_case(s).to_uppercase()
}

fn write_byte_list(f: &mut fmt::Formatter<'_>, bytes: &[u8]) -> fmt::Result {
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            write!(f, ", ")?;
        }
        write!(f, "0x{:02x}", b)?;
    }
    Ok(())
}

fn event_data_len(event: &EventDescriptor) -> usize {
    1 + event
        .fields
        .iter()
        .map(|field| field.offset as usize + field.size as usize)
        .max()
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{AccountEntry, ArgDescriptor, FieldIntent};
    use alloc::string::ToString;

    fn manifest() -> ProgramManifest {
        static FIELDS: &[FieldDescriptor] = &[
            FieldDescriptor {
                name: "authority",
                canonical_type: "Pubkey",
                size: 32,
                offset: 16,
                intent: FieldIntent::Authority,
            },
            FieldDescriptor {
                name: "balance",
                canonical_type: "u64",
                size: 8,
                offset: 48,
                intent: FieldIntent::Balance,
            },
        ];
        static LAYOUTS: &[LayoutManifest] = &[LayoutManifest {
            name: "vault",
            disc: 7,
            version: 1,
            layout_id: [1, 2, 3, 4, 5, 6, 7, 8],
            total_size: 56,
            field_count: 2,
            fields: FIELDS,
        }];
        static ARGS: &[ArgDescriptor] = &[ArgDescriptor {
            name: "amount",
            canonical_type: "u64",
            size: 8,
        }];
        static ACCOUNTS: &[AccountEntry] = &[
            AccountEntry {
                name: "vault",
                writable: true,
                signer: false,
                layout_ref: "vault",
                seeds: &[],
            },
            AccountEntry {
                name: "authority",
                writable: false,
                signer: true,
                layout_ref: "",
                seeds: &[],
            },
        ];
        static IXS: &[InstructionDescriptor] = &[InstructionDescriptor {
            name: "deposit",
            tag: 3,
            args: ARGS,
            accounts: ACCOUNTS,
            capabilities: &[],
            policy_pack: "",
            receipt_expected: false,
        }];
        static EVENT_FIELDS: &[FieldDescriptor] = &[FieldDescriptor {
            name: "amount",
            canonical_type: "u64",
            size: 8,
            offset: 4,
            intent: FieldIntent::Balance,
        }];
        static EVENTS: &[EventDescriptor] = &[EventDescriptor {
            name: "deposited",
            tag: 9,
            fields: EVENT_FIELDS,
        }];
        ProgramManifest {
            name: "vault_program",
            version: "0.1.0",
            description: "",
            layouts: LAYOUTS,
            layout_metadata: &[],
            instructions: IXS,
            events: EVENTS,
            policies: &[],
            compatibility_pairs: &[],
            tooling_hints: &[],
            contexts: &[],
        }
    }

    #[test]
    fn c_client_emits_layout_assertion_and_decoder() {
        let out = CClientGen(&manifest()).to_string();
        assert!(out.contains("hopper_assert_vault_layout"));
        assert!(out.contains("hopper_decode_vault"));
        assert!(out.contains("memcpy(out->authority.bytes, data + 16, 32u);"));
        assert!(out.contains("out->balance = hopper_read_le_u64(data + 48);"));
    }

    #[test]
    fn c_client_emits_instruction_and_event_builders() {
        let out = CClientGen(&manifest()).to_string();
        assert!(out.contains("hopper_build_deposit_data"));
        assert!(out.contains("hopper_write_le_u64(out + 1, args->amount);"));
        assert!(out.contains("hopper_decode_deposited_event"));
        assert!(out.contains("#define HOPPER_DEPOSITED_EVENT_DATA_LEN 13u"));
        assert!(out.contains("data[0] != HOPPER_DEPOSITED_EVENT_TAG"));
        assert!(out.contains("out->amount = hopper_read_le_u64(data + 5);"));
    }
}
