//! Go client generator.
//!
//! Emits a self-contained Go package from a [`ProgramManifest`]. The generated
//! package intentionally avoids a Solana transport dependency: it provides
//! account decoders, event decoders, account metadata, and instruction payloads
//! that callers can pass into their preferred Go Solana SDK.

extern crate alloc;

use alloc::{format, string::String};
use core::fmt;

use crate::{
    EventDescriptor, FieldDescriptor, InstructionDescriptor, LayoutManifest, ProgramManifest,
};

/// Full Go client emitter.
pub struct GoClientGen<'a>(pub &'a ProgramManifest);

impl<'a> fmt::Display for GoClientGen<'a> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let prog = self.0;

        writeln!(
            f,
            "// Code generated by `hopper compile --emit go`; DO NOT EDIT."
        )?;
        writeln!(f, "// Program: {} v{}", prog.name, prog.version)?;
        writeln!(f, "package hopperclient")?;
        writeln!(f)?;
        writeln!(f, "import (")?;
        writeln!(f, "\t\"encoding/binary\"")?;
        writeln!(f, "\t\"errors\"")?;
        writeln!(f, "\t\"fmt\"")?;
        writeln!(f, ")")?;
        writeln!(f)?;
        writeln!(f, "var _ = binary.LittleEndian")?;
        writeln!(f)?;
        writeln!(f, "const HeaderSize = 16")?;
        writeln!(f, "const LayoutIDOffset = 4")?;
        writeln!(f, "const LayoutIDLength = 8")?;
        writeln!(f)?;
        writeln!(f, "type Pubkey [32]byte")?;
        writeln!(f)?;
        writeln!(f, "type AccountMeta struct {{")?;
        writeln!(f, "\tPubkey Pubkey")?;
        writeln!(f, "\tIsSigner bool")?;
        writeln!(f, "\tIsWritable bool")?;
        writeln!(f, "\tLayout string")?;
        writeln!(f, "}}")?;
        writeln!(f)?;
        writeln!(f, "type Instruction struct {{")?;
        writeln!(f, "\tProgramID Pubkey")?;
        writeln!(f, "\tAccounts []AccountMeta")?;
        writeln!(f, "\tData []byte")?;
        writeln!(f, "}}")?;
        writeln!(f)?;
        writeln!(
            f,
            "var ErrBufferTooSmall = errors.New(\"hopper client: buffer too small\")"
        )?;
        writeln!(
            f,
            "var ErrTagMismatch = errors.New(\"hopper client: tag mismatch\")"
        )?;
        writeln!(f)?;
        writeln!(f, "type LayoutMismatchError struct {{")?;
        writeln!(f, "\tExpected [8]byte")?;
        writeln!(f, "\tActual [8]byte")?;
        writeln!(f, "}}")?;
        writeln!(f)?;
        writeln!(f, "func (e LayoutMismatchError) Error() string {{")?;
        writeln!(f, "\treturn fmt.Sprintf(\"hopper client: layout mismatch: expected %x got %x\", e.Expected, e.Actual)")?;
        writeln!(f, "}}")?;
        writeln!(f)?;
        writeln!(f, "func readLayoutID(data []byte) ([8]byte, error) {{")?;
        writeln!(f, "\tvar id [8]byte")?;
        writeln!(f, "\tif len(data) < HeaderSize {{")?;
        writeln!(f, "\t\treturn id, ErrBufferTooSmall")?;
        writeln!(f, "\t}}")?;
        writeln!(
            f,
            "\tcopy(id[:], data[LayoutIDOffset:LayoutIDOffset+LayoutIDLength])"
        )?;
        writeln!(f, "\treturn id, nil")?;
        writeln!(f, "}}")?;
        writeln!(f)?;
        writeln!(
            f,
            "func assertLayoutID(data []byte, expected [8]byte) error {{"
        )?;
        writeln!(f, "\tactual, err := readLayoutID(data)")?;
        writeln!(f, "\tif err != nil {{")?;
        writeln!(f, "\t\treturn err")?;
        writeln!(f, "\t}}")?;
        writeln!(f, "\tif actual != expected {{")?;
        writeln!(
            f,
            "\t\treturn LayoutMismatchError{{Expected: expected, Actual: actual}}"
        )?;
        writeln!(f, "\t}}")?;
        writeln!(f, "\treturn nil")?;
        writeln!(f, "}}")?;
        writeln!(f)?;

        for layout in prog.layouts.iter() {
            write_layout(f, layout)?;
        }

        for ix in prog.instructions.iter() {
            write_instruction(f, ix)?;
        }

        for event in prog.events.iter() {
            write_event(f, event)?;
        }

        Ok(())
    }
}

fn write_layout(f: &mut fmt::Formatter<'_>, layout: &LayoutManifest) -> fmt::Result {
    let pascal = pascal_case(layout.name);

    writeln!(f, "const {}Disc byte = {}", pascal, layout.disc)?;
    writeln!(f, "const {}Version byte = {}", pascal, layout.version)?;
    writeln!(f, "const {}TotalSize = {}", pascal, layout.total_size)?;
    write!(f, "var {}LayoutID = [8]byte{{", pascal)?;
    write_byte_list(f, &layout.layout_id)?;
    writeln!(f, "}}")?;
    writeln!(f)?;

    writeln!(f, "type {} struct {{", pascal)?;
    for field in layout.fields.iter() {
        writeln!(f, "\t{} {}", pascal_case(field.name), go_type(field))?;
    }
    writeln!(f, "}}")?;
    writeln!(f)?;

    writeln!(f, "func Assert{}Layout(data []byte) error {{", pascal)?;
    writeln!(f, "\treturn assertLayoutID(data, {}LayoutID)", pascal)?;
    writeln!(f, "}}")?;
    writeln!(f)?;

    writeln!(
        f,
        "func Decode{}(data []byte) ({}, error) {{",
        pascal, pascal
    )?;
    writeln!(f, "\tvar out {}", pascal)?;
    writeln!(f, "\tif err := Assert{}Layout(data); err != nil {{", pascal)?;
    writeln!(f, "\t\treturn out, err")?;
    writeln!(f, "\t}}")?;
    writeln!(f, "\tif len(data) < {}TotalSize {{", pascal)?;
    writeln!(f, "\t\treturn out, ErrBufferTooSmall")?;
    writeln!(f, "\t}}")?;
    for field in layout.fields.iter() {
        write_field_decode(f, field, "out.")?;
    }
    writeln!(f, "\treturn out, nil")?;
    writeln!(f, "}}")?;
    writeln!(f)?;
    Ok(())
}

fn write_instruction(f: &mut fmt::Formatter<'_>, ix: &InstructionDescriptor) -> fmt::Result {
    let pascal = pascal_case(ix.name);
    let data_len = 1usize + ix.args.iter().map(|arg| arg.size as usize).sum::<usize>();

    writeln!(f, "const {}Disc byte = {}", pascal, ix.tag)?;
    writeln!(f, "const {}DataLen = {}", pascal, data_len)?;
    writeln!(f)?;

    if !ix.args.is_empty() {
        writeln!(f, "type {}Args struct {{", pascal)?;
        for arg in ix.args.iter() {
            let fd = FieldDescriptor {
                name: arg.name,
                canonical_type: arg.canonical_type,
                size: arg.size,
                offset: 0,
                intent: crate::FieldIntent::Custom,
            };
            writeln!(f, "\t{} {}", pascal_case(arg.name), go_type(&fd))?;
        }
        writeln!(f, "}}")?;
        writeln!(f)?;
    }

    writeln!(f, "type {}Accounts struct {{", pascal)?;
    for account in ix.accounts.iter() {
        writeln!(f, "\t{} Pubkey", pascal_case(account.name))?;
    }
    writeln!(f, "}}")?;
    writeln!(f)?;

    write!(
        f,
        "func Build{}Instruction(programID Pubkey, accounts {}Accounts",
        pascal, pascal
    )?;
    if !ix.args.is_empty() {
        write!(f, ", args {}Args", pascal)?;
    }
    writeln!(f, ") (Instruction, error) {{")?;
    writeln!(f, "\tdata := make([]byte, {}DataLen)", pascal)?;
    writeln!(f, "\tdata[0] = {}Disc", pascal)?;
    let mut offset = 1usize;
    for arg in ix.args.iter() {
        write_arg_encode(
            f,
            arg.canonical_type,
            &format!("args.{}", pascal_case(arg.name)),
            offset,
            arg.size as usize,
        )?;
        offset += arg.size as usize;
    }
    // Program-derived accounts: this dependency-free client carries no PDA
    // crypto, so document the seed plan for host-side derivation (e.g.
    // solana.FindProgramAddress) rather than deriving inline.
    for account in ix.accounts.iter() {
        if crate::clientgen::account_is_auto_pda(account) {
            write!(f, "\t// PDA ")?;
            crate::clientgen::write_seed_plan(f, account)?;
            writeln!(f, " (derive host-side via solana.FindProgramAddress)")?;
        }
    }
    writeln!(f, "\tmetas := []AccountMeta{{")?;
    for account in ix.accounts.iter() {
        writeln!(
            f,
            "\t\t{{Pubkey: accounts.{}, IsSigner: {}, IsWritable: {}, Layout: \"{}\"}},",
            pascal_case(account.name),
            account.signer,
            account.writable,
            account.layout_ref
        )?;
    }
    writeln!(f, "\t}}")?;
    writeln!(
        f,
        "\treturn Instruction{{ProgramID: programID, Accounts: metas, Data: data}}, nil"
    )?;
    writeln!(f, "}}")?;
    writeln!(f)?;
    Ok(())
}

fn write_event(f: &mut fmt::Formatter<'_>, event: &EventDescriptor) -> fmt::Result {
    let pascal = pascal_case(event.name);
    let total_size = event_data_len(event);
    writeln!(f, "const {}EventTag byte = {}", pascal, event.tag)?;
    writeln!(f, "const {}EventDataLen = {}", pascal, total_size)?;
    writeln!(f)?;
    writeln!(f, "type {}Event struct {{", pascal)?;
    for field in event.fields.iter() {
        writeln!(f, "\t{} {}", pascal_case(field.name), go_type(field))?;
    }
    writeln!(f, "}}")?;
    writeln!(f)?;
    writeln!(
        f,
        "func Decode{}Event(data []byte) ({}Event, error) {{",
        pascal, pascal
    )?;
    writeln!(f, "\tvar out {}Event", pascal)?;
    writeln!(f, "\tif len(data) < {}EventDataLen {{", pascal)?;
    writeln!(f, "\t\treturn out, ErrBufferTooSmall")?;
    writeln!(f, "\t}}")?;
    writeln!(f, "\tif data[0] != {}EventTag {{", pascal)?;
    writeln!(f, "\t\treturn out, ErrTagMismatch")?;
    writeln!(f, "\t}}")?;
    for field in event.fields.iter() {
        write_event_field_decode(f, field, "out.")?;
    }
    writeln!(f, "\treturn out, nil")?;
    writeln!(f, "}}")?;
    writeln!(f)?;
    Ok(())
}

fn write_field_decode(
    f: &mut fmt::Formatter<'_>,
    field: &FieldDescriptor,
    target_prefix: &str,
) -> fmt::Result {
    write_field_decode_at(f, field, target_prefix, field.offset as usize)
}

fn write_event_field_decode(
    f: &mut fmt::Formatter<'_>,
    field: &FieldDescriptor,
    target_prefix: &str,
) -> fmt::Result {
    write_field_decode_at(f, field, target_prefix, field.offset as usize + 1)
}

fn write_field_decode_at(
    f: &mut fmt::Formatter<'_>,
    field: &FieldDescriptor,
    target_prefix: &str,
    offset: usize,
) -> fmt::Result {
    let name = pascal_case(field.name);
    let end = offset + field.size as usize;
    match field.canonical_type {
        "u8" => writeln!(f, "\t{}{} = data[{}]", target_prefix, name, offset),
        "i8" => writeln!(f, "\t{}{} = int8(data[{}])", target_prefix, name, offset),
        "u16" => writeln!(
            f,
            "\t{}{} = binary.LittleEndian.Uint16(data[{}:{}])",
            target_prefix, name, offset, end
        ),
        "i16" => writeln!(
            f,
            "\t{}{} = int16(binary.LittleEndian.Uint16(data[{}:{}]))",
            target_prefix, name, offset, end
        ),
        "u32" => writeln!(
            f,
            "\t{}{} = binary.LittleEndian.Uint32(data[{}:{}])",
            target_prefix, name, offset, end
        ),
        "i32" => writeln!(
            f,
            "\t{}{} = int32(binary.LittleEndian.Uint32(data[{}:{}]))",
            target_prefix, name, offset, end
        ),
        "u64" | "WireU64" => writeln!(
            f,
            "\t{}{} = binary.LittleEndian.Uint64(data[{}:{}])",
            target_prefix, name, offset, end
        ),
        "i64" | "WireI64" => writeln!(
            f,
            "\t{}{} = int64(binary.LittleEndian.Uint64(data[{}:{}]))",
            target_prefix, name, offset, end
        ),
        "bool" | "WireBool" => writeln!(f, "\t{}{} = data[{}] != 0", target_prefix, name, offset),
        "Pubkey" => writeln!(
            f,
            "\tcopy({}{}[:], data[{}:{}])",
            target_prefix, name, offset, end
        ),
        _ => writeln!(
            f,
            "\tcopy({}{}[:], data[{}:{}])",
            target_prefix, name, offset, end
        ),
    }
}

fn write_arg_encode(
    f: &mut fmt::Formatter<'_>,
    canonical: &str,
    expr: &str,
    offset: usize,
    size: usize,
) -> fmt::Result {
    let end = offset + size;
    match canonical {
        "u8" => writeln!(f, "\tdata[{}] = {}", offset, expr),
        "i8" => writeln!(f, "\tdata[{}] = byte({})", offset, expr),
        "u16" => writeln!(
            f,
            "\tbinary.LittleEndian.PutUint16(data[{}:{}], {})",
            offset, end, expr
        ),
        "i16" => writeln!(
            f,
            "\tbinary.LittleEndian.PutUint16(data[{}:{}], uint16({}))",
            offset, end, expr
        ),
        "u32" => writeln!(
            f,
            "\tbinary.LittleEndian.PutUint32(data[{}:{}], {})",
            offset, end, expr
        ),
        "i32" => writeln!(
            f,
            "\tbinary.LittleEndian.PutUint32(data[{}:{}], uint32({}))",
            offset, end, expr
        ),
        "u64" | "WireU64" => writeln!(
            f,
            "\tbinary.LittleEndian.PutUint64(data[{}:{}], {})",
            offset, end, expr
        ),
        "i64" | "WireI64" => writeln!(
            f,
            "\tbinary.LittleEndian.PutUint64(data[{}:{}], uint64({}))",
            offset, end, expr
        ),
        "bool" | "WireBool" => {
            writeln!(f, "\tif {} {{", expr)?;
            writeln!(f, "\t\tdata[{}] = 1", offset)?;
            writeln!(f, "\t}}")
        }
        "Pubkey" => writeln!(f, "\tcopy(data[{}:{}], {}[:])", offset, end, expr),
        _ => writeln!(f, "\tcopy(data[{}:{}], {}[:])", offset, end, expr),
    }
}

fn go_type(field: &FieldDescriptor) -> String {
    match field.canonical_type {
        "u8" => "byte".into(),
        "i8" => "int8".into(),
        "u16" => "uint16".into(),
        "i16" => "int16".into(),
        "u32" => "uint32".into(),
        "i32" => "int32".into(),
        "u64" | "WireU64" => "uint64".into(),
        "i64" | "WireI64" => "int64".into(),
        "bool" | "WireBool" => "bool".into(),
        "Pubkey" => "Pubkey".into(),
        _ => format!("[{}]byte", field.size),
    }
}

fn pascal_case(s: &str) -> String {
    let mut out = String::new();
    let mut upper_next = true;
    for c in s.chars() {
        if c == '_' || c == '-' || c == ' ' {
            upper_next = true;
        } else if upper_next {
            out.extend(c.to_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn write_byte_list(f: &mut fmt::Formatter<'_>, bytes: &[u8]) -> fmt::Result {
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            write!(f, ", ")?;
        }
        write!(f, "0x{:02x}", b)?;
    }
    Ok(())
}

fn event_data_len(event: &EventDescriptor) -> usize {
    1 + event
        .fields
        .iter()
        .map(|field| field.offset as usize + field.size as usize)
        .max()
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{AccountEntry, ArgDescriptor, FieldIntent};
    use alloc::string::ToString;

    fn manifest() -> ProgramManifest {
        static FIELDS: &[FieldDescriptor] = &[
            FieldDescriptor {
                name: "authority",
                canonical_type: "Pubkey",
                size: 32,
                offset: 16,
                intent: FieldIntent::Authority,
            },
            FieldDescriptor {
                name: "balance",
                canonical_type: "u64",
                size: 8,
                offset: 48,
                intent: FieldIntent::Balance,
            },
        ];
        static LAYOUTS: &[LayoutManifest] = &[LayoutManifest {
            name: "vault",
            disc: 7,
            version: 1,
            layout_id: [1, 2, 3, 4, 5, 6, 7, 8],
            total_size: 56,
            field_count: 2,
            fields: FIELDS,
        }];
        static ARGS: &[ArgDescriptor] = &[ArgDescriptor {
            name: "amount",
            canonical_type: "u64",
            size: 8,
            encoding: crate::ArgEncoding::Fixed,
        }];
        static ACCOUNTS: &[AccountEntry] = &[
            AccountEntry {
                name: "vault",
                writable: true,
                signer: false,
                layout_ref: "vault",
                seeds: &["b\"vault\"", "authority.key().as_ref()"],
            },
            AccountEntry {
                name: "authority",
                writable: false,
                signer: true,
                layout_ref: "",
                seeds: &[],
            },
        ];
        static IXS: &[InstructionDescriptor] = &[InstructionDescriptor {
            name: "deposit",
            tag: 3,
            discriminator: &[3],
            args: ARGS,
            accounts: ACCOUNTS,
            remaining_accounts: None,
            capabilities: &[],
            policy_pack: "",
            receipt_expected: false,
            strict_writes: false,
            write_ranges: &[],
            parametric_write_ranges: &[],
            mutation_complete: false,
            lamport_accounts: &[],
            cu_estimate: 0,
        }];
        static EVENT_FIELDS: &[FieldDescriptor] = &[FieldDescriptor {
            name: "amount",
            canonical_type: "u64",
            size: 8,
            offset: 4,
            intent: FieldIntent::Balance,
        }];
        static EVENTS: &[EventDescriptor] = &[EventDescriptor {
            name: "deposited",
            tag: 9,
            fields: EVENT_FIELDS,
        }];
        ProgramManifest {
            name: "vault_program",
            version: "0.1.0",
            description: "",
            layouts: LAYOUTS,
            layout_metadata: &[],
            instructions: IXS,
            events: EVENTS,
            policies: &[],
            compatibility_pairs: &[],
            tooling_hints: &[],
            contexts: &[],
        }
    }

    #[test]
    fn go_client_emits_layout_assertion_and_decoder() {
        let out = GoClientGen(&manifest()).to_string();
        assert!(out.contains("func AssertVaultLayout(data []byte) error"));
        assert!(out.contains("func DecodeVault(data []byte) (Vault, error)"));
        assert!(out.contains("copy(out.Authority[:], data[16:48])"));
        assert!(out.contains("out.Balance = binary.LittleEndian.Uint64(data[48:56])"));
    }

    #[test]
    fn go_client_emits_instruction_and_event_builders() {
        let out = GoClientGen(&manifest()).to_string();
        assert!(out.contains("func BuildDepositInstruction(programID Pubkey, accounts DepositAccounts, args DepositArgs) (Instruction, error)"));
        assert!(out.contains("binary.LittleEndian.PutUint64(data[1:9], args.Amount)"));
        assert!(out.contains("func DecodeDepositedEvent(data []byte) (DepositedEvent, error)"));
        assert!(out.contains("const DepositedEventDataLen = 13"));
        assert!(out.contains("data[0] != DepositedEventTag"));
        assert!(out.contains("out.Amount = binary.LittleEndian.Uint64(data[5:13])"));
    }

    #[test]
    fn go_client_documents_pda_seed_plan() {
        // Go is dependency-free (no PDA crypto), so the classified seed plan is
        // surfaced as a comment for host-side derivation.
        let out = GoClientGen(&manifest()).to_string();
        assert!(out.contains(
            "// PDA vault: literal \"vault\", account authority (derive host-side via solana.FindProgramAddress)"
        ));
        // The account remains caller-provided in the metas.
        assert!(out.contains("{Pubkey: accounts.Vault, IsSigner: false, IsWritable: true"));
    }
}
